games = {};

games.easy = [
{letters: 'KOGESS', words: ['EGO', 'KEG', 'EGOS', 'GOES', 'KEGS']},
{letters: 'ELSSES', words: ['EEL', 'LEE', 'SEE', 'EELS', 'ELSE', 'LESS', 'SEES']},
{letters: 'YGVAEA', words: ['AGE', 'AYE', 'GAY', 'GAVE']},
{letters: 'EUSRNC', words: ['CUE', 'CUR', 'RUE', 'RUN', 'SUE', 'SUN', 'URN', 'USE', 'CUES', 'CURE', 'RUES', 'RUNE', 'RUNS', 'RUSE', 'SURE', 'URNS', 'USER', 'CURES', 'CURSE', 'NURSE', 'RUNES']},
{letters: 'IERNSA', words: ['AIR', 'ARE', 'EAR', 'ERA', 'INS', 'IRE', 'RAN', 'SEA', 'SIN', 'SIR', 'AIRS', 'ARES', 'ARSE', 'EARN', 'EARS', 'ERAS', 'NEAR', 'RAIN', 'REIN', 'RISE', 'SANE', 'SARI', 'SEAR', 'SINE', 'SIRE', 'ARISE', 'EARNS', 'NEARS', 'RAINS', 'RAISE', 'REINS', 'RESIN', 'RINSE', 'RISEN', 'SANER', 'SIREN', 'SNARE', 'ARISEN']},
{letters: 'NCWJOI', words: ['CON', 'COW', 'ION', 'NOW', 'OWN', 'WIN', 'WON', 'COIN', 'ICON', 'JOIN']},
{letters: 'MRTIEG', words: ['GEM', 'GET', 'IRE', 'MET', 'RIG', 'RIM', 'TIE', 'EMIR', 'EMIT', 'GERM', 'GRIM', 'GRIT', 'ITEM', 'MIRE', 'MITE', 'RITE', 'TERM', 'TIER', 'TIME', 'TIRE', 'TRIM', 'GRIME', 'MERIT', 'REMIT', 'TIGER', 'TIMER']},
{letters: 'TOUGGT', words: ['GOT', 'GUT', 'OUT', 'TOT', 'TUG', 'GOUT', 'TOUT']},
{letters: 'EGDBZT', words: ['BED', 'BEG', 'BET', 'GET', 'DEBT']},
{letters: 'THEIRN', words: ['HEN', 'HER', 'HIT', 'IRE', 'NET', 'NIT', 'TEN', 'THE', 'TIE', 'TIN', 'HEIR', 'HINT', 'HIRE', 'REIN', 'RENT', 'RITE', 'THEN', 'THIN', 'TIER', 'TIRE', 'INERT', 'INTER', 'THEIR']},
{letters: 'AEEPSN', words: ['APE', 'NAP', 'PAN', 'PAS', 'PEA', 'PEN', 'SAP', 'SEA', 'SEE', 'SPA', 'APES', 'EASE', 'NAPE', 'NAPS', 'PANE', 'PANS', 'PEAS', 'PENS', 'SANE', 'SEEN', 'SEEP', 'SNAP', 'SPAN', 'ASPEN', 'NAPES', 'PANES']},
{letters: 'OOETVE', words: ['EVE', 'TEE', 'TOE', 'TOO', 'VET', 'VETO', 'VOTE']},
{letters: 'DSRREE', words: ['ERR', 'RED', 'SEE', 'DEER', 'ERRS', 'REDS', 'REED', 'SEED', 'SEER', 'ERRED', 'REEDS']},
{letters: 'RYNRNA', words: ['ANY', 'NAY', 'RAN', 'RAY', 'YARN']},
{letters: 'EODILG', words: ['DIE', 'DIG', 'DOE', 'DOG', 'EGO', 'GEL', 'GOD', 'LED', 'LEG', 'LID', 'LIE', 'LOG', 'ODE', 'OIL', 'OLD', 'DELI', 'DOLE', 'GELD', 'GILD', 'GOLD', 'IDLE', 'IDOL', 'LIED', 'OGLE', 'GLIDE', 'LODGE', 'OGLED', 'OILED']},
{letters: 'IMLRPN', words: ['IMP', 'LIP', 'NIL', 'NIP', 'PIN', 'RIM', 'RIP', 'LIMP', 'PRIM']},
{letters: 'SHECES', words: ['HES', 'SEE', 'SHE', 'SEES', 'SHES', 'CHESS']},
{letters: 'NRCAEM', words: ['ACE', 'ARC', 'ARE', 'ARM', 'CAM', 'CAN', 'CAR', 'EAR', 'ERA', 'MAN', 'MAR', 'MEN', 'RAM', 'RAN', 'ACNE', 'ACRE', 'AMEN', 'CAME', 'CANE', 'CARE', 'CRAM', 'EARN', 'MACE', 'MANE', 'MARE', 'MEAN', 'NAME', 'NEAR', 'RACE', 'REAM', 'CRANE', 'CREAM']},
{letters: 'FWASRU', words: ['FAR', 'FUR', 'RAW', 'SAW', 'WAR', 'WAS', 'FURS', 'SURF', 'WARS']},
{letters: 'TULCEA', words: ['ACE', 'ACT', 'ALE', 'ATE', 'CAT', 'CUE', 'CUT', 'EAT', 'LET', 'TEA', 'CLUE', 'CULT', 'CUTE', 'LACE', 'LATE', 'LUTE', 'TALC', 'TALE', 'ACUTE', 'CLEAT']},
];

games.medium = [
{letters: 'TAMIET', words: ['AIM', 'ATE', 'EAT', 'ETA', 'MAT', 'MET', 'TAM', 'TAT', 'TEA', 'TIE', 'TIT', 'EMIT', 'ITEM', 'MATE', 'MEAT', 'MITE', 'MITT', 'TAME', 'TEAM', 'TEAT', 'TIME', 'MATTE']},
{letters: 'RSLOAE', words: ['ALE', 'ARE', 'EAR', 'ERA', 'LEA', 'OAR', 'ORE', 'ROE', 'SEA', 'SOL', 'ALES', 'ALOE', 'ALSO', 'ARES', 'ARSE', 'EARL', 'EARS', 'ERAS', 'LEAS', 'LORE', 'LOSE', 'OARS', 'ORAL', 'ORES', 'REAL', 'ROES', 'ROLE', 'ROSE', 'SALE', 'SEAL', 'SEAR', 'SLOE', 'SOAR', 'SOLE', 'SORE', 'ALOES', 'AROSE', 'EARLS', 'LASER', 'LOSER', 'ORALS', 'REALS', 'ROLES', 'SOLAR']},
{letters: 'SISGDP', words: ['DIG', 'DIP', 'DIS', 'IDS', 'PIG', 'PIS', 'SIP', 'SIS', 'DIGS', 'DIPS', 'PIGS', 'PISS', 'SIPS']},
{letters: 'ILEHAD', words: ['AID', 'AIL', 'ALE', 'DIE', 'HAD', 'HID', 'HIE', 'LAD', 'LEA', 'LED', 'LEI', 'LID', 'LIE', 'AIDE', 'DALE', 'DEAL', 'DELI', 'DIAL', 'HAIL', 'HALE', 'HEAD', 'HEAL', 'HELD', 'HIDE', 'HIED', 'IDEA', 'IDLE', 'LADE', 'LAID', 'LEAD', 'LIED', 'AILED', 'HALED', 'IDEAL', 'HAILED']},
{letters: 'SUSEIS', words: ['SIS', 'SUE', 'USE', 'SUES', 'USES', 'ISSUE', 'SISES', 'ISSUES']},
{letters: 'EIISNC', words: ['ICE', 'INS', 'SIC', 'SIN', 'ICES', 'NICE', 'SINE', 'SINCE', 'INCISE']},
{letters: 'TODDDW', words: ['DOT', 'ODD', 'TOW', 'TWO', 'WOT']},
{letters: 'SSOSEA', words: ['SEA', 'SASS', 'SEAS', 'ASSES', 'OASES']},
{letters: 'TIESDI', words: ['DIE', 'DIS', 'IDS', 'ITS', 'SET', 'SIT', 'TIE', 'DIES', 'DIET', 'EDIT', 'IDES', 'SIDE', 'SITE', 'TIDE', 'TIED', 'TIES', 'DIETS', 'EDITS', 'SITED', 'TIDES', 'TIDIES']},
{letters: 'CUUIRN', words: ['CUR', 'RUN', 'URN', 'RUIN', 'URIC', 'INCUR']},
{letters: 'RDAANE', words: ['AND', 'ARE', 'DEN', 'EAR', 'END', 'ERA', 'RAN', 'RED', 'AREA', 'DARE', 'DARN', 'DEAN', 'DEAR', 'EARN', 'NEAR', 'NERD', 'READ', 'REND', 'ARENA']},
{letters: 'ANASPO', words: ['ASP', 'NAP', 'PAN', 'PAS', 'SAP', 'SON', 'SOP', 'SPA', 'NAPS', 'PANS', 'SNAP', 'SOAP', 'SPAN']},
{letters: 'TSSLCE', words: ['LET', 'SET', 'LESS', 'LEST', 'LETS', 'SECS', 'SECT', 'SETS', 'SECTS']},
{letters: 'EOTDLI', words: ['DIE', 'DOE', 'DOT', 'LED', 'LEI', 'LET', 'LID', 'LIE', 'LIT', 'LOT', 'ODE', 'OIL', 'OLD', 'TIE', 'TOE', 'DELI', 'DIET', 'DOLE', 'DOLT', 'DOTE', 'EDIT', 'IDLE', 'IDOL', 'LIED', 'LITE', 'LODE', 'TIDE', 'TIED', 'TILE', 'TOED', 'TOIL', 'TOLD', 'OILED', 'OLDIE', 'TILDE', 'TILED', 'TOILED']},
{letters: 'CLNEIL', words: ['ELL', 'ICE', 'ILL', 'LEI', 'LIE', 'NIL', 'CELL', 'LICE', 'LIEN', 'LINE', 'NICE']},
{letters: 'FSTTEE', words: ['FEE', 'SEE', 'SET', 'TEE', 'FEES', 'FEET', 'FEST', 'TEES', 'TEST']},
{letters: 'NURLIN', words: ['INN', 'NIL', 'NUN', 'RUN', 'URN', 'RUIN']},
{letters: 'HAIEPG', words: ['AGE', 'APE', 'GAP', 'HAG', 'HEP', 'HIE', 'HIP', 'PEA', 'PEG', 'PIE', 'PIG', 'GAPE', 'HEAP', 'PAGE']},
{letters: 'CCLTOY', words: ['COT', 'COY', 'LOT', 'TOY', 'CLOT', 'CLOY', 'COLT']},
{letters: 'ARSTER', words: ['ARE', 'ART', 'ATE', 'EAR', 'EAT', 'ERA', 'ERR', 'ETA', 'RAT', 'SAT', 'SEA', 'SET', 'TAR', 'TEA', 'ARES', 'ARSE', 'ARTS', 'EARS', 'EAST', 'EATS', 'ERAS', 'ERRS', 'RARE', 'RATE', 'RATS', 'REAR', 'REST', 'SATE', 'SEAR', 'SEAT', 'STAR', 'TARE', 'TARS', 'TEAR', 'TEAS', 'ASTER', 'RARES', 'RATES', 'REARS', 'STARE', 'TARES', 'TEARS', 'ARREST', 'RAREST', 'RASTER']},
];

games.hard = [
{letters: 'PRHEYA', words: ['APE', 'ARE', 'AYE', 'EAR', 'ERA', 'HAE', 'HAP', 'HAY', 'HEP', 'HER', 'HEY', 'PAH', 'PAR', 'PAY', 'PEA', 'PER', 'PRY', 'PYA', 'PYE', 'RAH', 'RAP', 'RAY', 'REP', 'RYA', 'RYE', 'YAH', 'YAP', 'YEA', 'YEP', 'YER', 'EYRA', 'HARE', 'HARP', 'HEAP', 'HEAR', 'HYPE', 'PARE', 'PEAR', 'PRAY', 'PREY', 'PYRE', 'RAPE', 'REAP', 'RHEA', 'YARE', 'YEAH', 'YEAR', 'APERY', 'HARPY', 'HYPER', 'PAYER', 'REPAY']},
{letters: 'OUSNNA', words: ['ANS', 'NON', 'NUN', 'NUS', 'SON', 'SOU', 'SUN', 'ANON', 'ANUS', 'NAOS', 'NOUN', 'NOUS', 'NUNS', 'ONUS', 'SUNN', 'ANONS', 'NOUNS']},
{letters: 'IETASM', words: ['AIM', 'AIS', 'AIT', 'AMI', 'ATE', 'EAT', 'EMS', 'ETA', 'ISM', 'ITS', 'MAS', 'MAT', 'MES', 'MET', 'SAT', 'SEA', 'SET', 'SIT', 'TAM', 'TEA', 'TIE', 'AIMS', 'AMIE', 'EAST', 'EATS', 'EMIT', 'ETAS', 'ITEM', 'MAST', 'MATE', 'MATS', 'MEAT', 'MESA', 'MIST', 'MITE', 'SAME', 'SATE', 'SATI', 'SEAM', 'SEAT', 'SEMI', 'SIMA', 'SITE', 'STEM', 'TAME', 'TAMS', 'TEAM', 'TEAS', 'TIES', 'TIME', 'EMITS', 'ITEMS', 'MATES', 'MEATS', 'METIS', 'MITES', 'SATEM', 'SMITE', 'STEAM', 'TAMES', 'TAMIS', 'TEAMS', 'TIMES', 'SAMITE']},
{letters: 'TETSVI', words: ['ITS', 'SET', 'SIT', 'TIE', 'TIT', 'VET', 'VIE', 'SETT', 'SITE', 'STET', 'TEST', 'TIES', 'TITS', 'VEST', 'VETS', 'VIES', 'VISE']},
{letters: 'MKELTI', words: ['ELK', 'ELM', 'ILK', 'KIT', 'LEI', 'LEK', 'LET', 'LIE', 'LIT', 'MEL', 'MET', 'MIL', 'TIE', 'TIL', 'EMIT', 'ITEM', 'KELT', 'KILT', 'KITE', 'LIKE', 'LIME', 'LITE', 'MELT', 'MIKE', 'MILE', 'MILK', 'MILT', 'MITE', 'TILE', 'TIME']},
{letters: 'GLRASC', words: ['ARC', 'CAR', 'GAL', 'GAR', 'GAS', 'LAC', 'LAG', 'LAR', 'RAG', 'SAC', 'SAG', 'SAL', 'ARCS', 'CARL', 'CARS', 'CRAG', 'GALS', 'GARS', 'LAGS', 'RAGS', 'SCAR', 'SLAG', 'CRAGS', 'SCRAG']},
{letters: 'RVUAND', words: ['AND', 'DUN', 'RAN', 'RUN', 'URN', 'VAN', 'DARN', 'NARD', 'RAND']},
{letters: 'LEPSEC', words: ['EEL', 'ELS', 'LEE', 'PEC', 'PEE', 'PES', 'SEE', 'EELS', 'ELSE', 'LEES', 'PECS', 'PEEL', 'PEES', 'SEEL', 'SEEP', 'SPEC', 'CLEPE', 'PEELS', 'SLEEP']},
{letters: 'EDHNSI', words: ['DEN', 'DIE', 'DIN', 'DIS', 'EDH', 'END', 'ENS', 'HEN', 'HES', 'HID', 'HIE', 'HIN', 'HIS', 'IDS', 'INS', 'SHE', 'SIN', 'DENS', 'DIES', 'DINE', 'DINS', 'DISH', 'ENDS', 'HENS', 'HIDE', 'HIED', 'HIES', 'HIND', 'HINS', 'IDES', 'NIDE', 'SEND', 'SHED', 'SHIN', 'SIDE', 'SINE', 'SINH', 'DINES', 'HIDES', 'HINDS', 'SHEND', 'SHIED', 'SHINE', 'SNIDE', 'SHINED']},
{letters: 'NALFPR', words: ['ALP', 'FAN', 'FAR', 'LAP', 'LAR', 'NAP', 'PAL', 'PAN', 'PAR', 'RAN', 'RAP', 'FARL', 'FLAN', 'FLAP', 'FRAP', 'PLAN']},
{letters: 'NNADLS', words: ['ADS', 'AND', 'ANS', 'LAD', 'SAD', 'SAL', 'LADS', 'LAND', 'SAND', 'LANDS']},
{letters: 'OUNTAI', words: ['AIN', 'AIT', 'ANT', 'ION', 'NIT', 'NOT', 'NUT', 'OAT', 'OUI', 'OUT', 'TAN', 'TAU', 'TIN', 'TON', 'TUI', 'TUN', 'UNI', 'ANTI', 'AUNT', 'AUTO', 'INTO', 'IOTA', 'TAIN', 'TUNA', 'UNIT', 'UNTO']},
{letters: 'TNAIPM', words: ['AIM', 'AIN', 'AIT', 'AMI', 'AMP', 'ANT', 'APT', 'IMP', 'MAN', 'MAP', 'MAT', 'NAP', 'NIM', 'NIP', 'NIT', 'PAN', 'PAT', 'PIN', 'PIT', 'TAM', 'TAN', 'TAP', 'TIN', 'TIP', 'ANTI', 'MAIN', 'MINT', 'NIPA', 'PAIN', 'PANT', 'PINT', 'PITA', 'TAIN', 'TAMP', 'INAPT', 'MATIN', 'PAINT', 'PATIN', 'PINTA', 'PITMAN']},
{letters: 'EAERMA', words: ['ARE', 'ARM', 'EAR', 'ERA', 'ERE', 'MAR', 'RAM', 'AREA', 'MARA', 'MARE', 'MERE', 'REAM']},
{letters: 'GLCSRE', words: ['ELS', 'ERG', 'GEL', 'GRE', 'LEG', 'ERGS', 'GELS', 'LEGS']},
{letters: 'TITUPI', words: ['PIT', 'PUT', 'TIP', 'TIT', 'TUI', 'TUT', 'PUTT', 'TITI']},
{letters: 'RFERTN', words: ['EFT', 'ERR', 'FEN', 'FER', 'NET', 'REF', 'TEN', 'FERN', 'FRET', 'REFT', 'RENT', 'TERN', 'TREF']},
{letters: 'IESIQD', words: ['DIE', 'DIS', 'IDS', 'DIES', 'IDES', 'SIDE']},
{letters: 'GPPARC', words: ['ARC', 'CAP', 'CAR', 'GAP', 'GAR', 'PAP', 'PAR', 'RAG', 'RAP', 'CARP', 'CRAG', 'CRAP']},
{letters: 'TDNIAV', words: ['AID', 'AIN', 'AIT', 'AND', 'ANT', 'DIN', 'DIT', 'NIT', 'TAD', 'TAN', 'TIN', 'VAN', 'VAT', 'VIA', 'ADIT', 'ANTI', 'AVID', 'DINT', 'DIVA', 'TAIN', 'VAIN', 'VINA', 'VITA', 'DAVIT', 'DIVAN', 'VIAND']},
];

games.insane = [
{letters: 'CMICTL', words: ['CCM', 'CLI', 'LIM', 'LIT', 'LTM', 'MCI', 'MIC', 'MIL', 'MIT', 'TIC', 'TIL', 'TIM', 'TLC', 'CLIT', 'MILT']},
{letters: 'IECICA', words: ['ACE', 'AEC', 'CAI', 'CIA', 'CIE', 'ECC', 'ICE', 'ACCE', 'CACE', 'CACI', 'CAIC', 'CECA', 'CACEI', 'ICICA']},
{letters: 'BERNCB', words: ['BEC', 'BEN', 'BER', 'CRE', 'EBB', 'EBN', 'ECB', 'NBE', 'NEB', 'REB', 'REN', 'BREN', 'CERN']},
{letters: 'OSLSPA', words: ['ALO', 'ALP', 'ALS', 'APL', 'ASL', 'ASP', 'LAO', 'LAP', 'LAS', 'LOA', 'LOP', 'LOS', 'OAS', 'OLA', 'OLP', 'OPA', 'OPS', 'PAL', 'PAS', 'POA', 'POL', 'SAL', 'SAO', 'SAP', 'SLA', 'SOL', 'SOP', 'SPA', 'SPL', 'SPS', 'SSP', 'ALOP', 'ALPS', 'ALSO', 'ASOP', 'ASPS', 'LAOS', 'LAPS', 'LASS', 'LOPS', 'LOSS', 'OPAL', 'OSSA', 'PALS', 'PASO', 'PASS', 'POAS', 'POLS', 'SALP', 'SALS', 'SAPO', 'SAPS', 'SLAP', 'SLOP', 'SOAP', 'SOLA', 'SOLS', 'SOPS', 'SPAS', 'ASLOP', 'LASSO', 'OPALS', 'OSSAL', 'PASSO', 'PLASS', 'PSOAS', 'SALOP', 'SALPS', 'SLAPS', 'SLOPS', 'SOAPS', 'SOLAS', 'SALOPS']},
{letters: 'LNNEIL', words: ['ELI', 'ELL', 'ILE', 'ILL', 'INN', 'LEI', 'LIE', 'NEI', 'NIE', 'NIL', 'NNE', 'ELLI', 'INNE', 'LIEN', 'LILE', 'LINE', 'LINN', 'NEIN', 'NILE', 'NILL', 'NINE', 'ENLIL', 'LENIN', 'LINEN']},
{letters: 'ANGMDI', words: ['AID', 'AIM', 'AIN', 'AMI', 'AND', 'DAG', 'DAM', 'DAN', 'DIG', 'DIM', 'DIN', 'DNA', 'GAD', 'GAM', 'GAN', 'GID', 'GIM', 'GIN', 'IDA', 'ING', 'MAD', 'MAN', 'MAN', 'MGD', 'MIA', 'MID', 'MIG', 'MNA', 'NAD', 'NAG', 'NAM', 'NID', 'NIG', 'NIM', 'ADMI', 'AGIN', 'AGNI', 'AMID', 'AMIN', 'DAIN', 'DAMN', 'DANG', 'DIAN', 'DING', 'GADI', 'GAID', 'GAIN', 'IGAD', 'IMAN', 'INGA', 'MAGI', 'MAID', 'MAIN', 'MAND', 'MANG', 'MANI', 'MIAN', 'MIDN', 'MIND', 'MING', 'NAGI', 'NAID', 'NAIG', 'NGAI', 'GAMIN', 'MANDI', 'MANGI', 'MANID']},
{letters: 'ESRGPA', words: ['AER', 'AES', 'AGE', 'AGS', 'APE', 'APR', 'ARE', 'ARG', 'ARS', 'ASE', 'ASG', 'ASP', 'EAR', 'EAS', 'EPA', 'ERA', 'ERG', 'ERS', 'ESR', 'GAE', 'GAP', 'GAR', 'GAS', 'GPS', 'GRA', 'GRE', 'GRS', 'PAR', 'PAS', 'PEA', 'PEG', 'PER', 'PES', 'PRE', 'RAG', 'RAP', 'RAS', 'REA', 'REP', 'SAG', 'SAP', 'SAR', 'SEA', 'SEG', 'SPA', 'AGES', 'AGRE', 'APER', 'APES', 'APSE', 'AREG', 'ARES', 'ARSE', 'EARS', 'ERAS', 'ERGS', 'GAES', 'GAPE', 'GAPS', 'GARE', 'GARS', 'GASP', 'GEAR', 'GRAS', 'GRES', 'PAGE', 'PARE', 'PARS', 'PASE', 'PEAG', 'PEAR', 'PEAS', 'PEGA', 'PEGS', 'PESA', 'PRAG', 'RAGE', 'RAGS', 'RAPE', 'RAPS', 'RASP', 'REAP', 'REGS', 'REPS', 'SAGE', 'SARE', 'SEAR', 'SEPG', 'SERG', 'SPAE', 'SPAG', 'SPAR', 'AGERS', 'APERS', 'ASPER', 'GAPER', 'GAPES', 'GARSE', 'GEARS', 'GRAPE', 'GRASP', 'PAGER', 'PAGES', 'PARES', 'PARGE', 'PARSE', 'PEAGS', 'PEARS', 'PRASE', 'PRESA', 'RAGES', 'RAPES', 'REAPS', 'REPAS', 'SAGER', 'SARGE', 'SEGAR', 'SPAER', 'SPARE', 'SPEAR', 'SPRAG', 'GAPERS', 'GASPER', 'GRAPES', 'PAGERS', 'PARGES', 'SPARGE']},
{letters: 'DNLERS', words: ['DEN', 'DES', 'DLE', 'DSR', 'ELD', 'ELS', 'END', 'ENS', 'ERD', 'ERS', 'ESD', 'ESR', 'LED', 'LER', 'LES', 'LNR', 'LSD', 'NED', 'RED', 'REN', 'RLD', 'RLE', 'SED', 'SEL', 'DELS', 'DENS', 'DERN', 'ELDS', 'ENDS', 'LEDS', 'LEND', 'LENS', 'NEDS', 'NERD', 'REDS', 'REND', 'RENS', 'SELD', 'SEND', 'SLED', 'SNED', 'DERNS', 'LENDS', 'NERDS', 'RENDS']},
{letters: 'EAUIPS', words: ['AES', 'AIS', 'APE', 'ASE', 'ASP', 'EAS', 'EAU', 'EPA', 'EPI', 'IPS', 'ISE', 'PAS', 'PAU', 'PEA', 'PES', 'PIA', 'PIE', 'PIS', 'PSI', 'PUA', 'PUS', 'SAI', 'SAP', 'SAU', 'SEA', 'SEI', 'SIE', 'SIP', 'SPA', 'SUE', 'SUI', 'SUP', 'UPS', 'USA', 'USE', 'APES', 'APIS', 'APSE', 'APSU', 'APUS', 'EAUS', 'ESAU', 'IPSE', 'PAIS', 'PASE', 'PASI', 'PEAI', 'PEAS', 'PESA', 'PIAS', 'PIES', 'PISA', 'PIUA', 'PIUS', 'PSIA', 'SAIP', 'SIPE', 'SPAE', 'SPIE', 'SPUE', 'SUPA', 'SUPE', 'UPAS', 'PAISE', 'PAUSE', 'SEPIA']},
{letters: 'SOISSP', words: ['IOS', 'IPO', 'IPS', 'ISO', 'OIS', 'OPS', 'OSI', 'PIS', 'POI', 'PSI', 'SIP', 'SIS', 'SOP', 'SPS', 'SSP', 'IPSO', 'ISOS', 'PISO', 'PISS', 'POIS', 'PSIS', 'SIPS', 'SISS', 'SOPS', 'SOSS', 'PISOS', 'SPISS']},
{letters: 'ISRTAB', words: ['ABS', 'ABT', 'AIR', 'AIS', 'AIT', 'ARB', 'ARS', 'ART', 'ASB', 'AST', 'BAI', 'BAR', 'BAS', 'BAT', 'BIS', 'BIT', 'BRA', 'IBA', 'IRA', 'IRS', 'IST', 'ITS', 'RAB', 'RAI', 'RAS', 'RAT', 'RIA', 'RIB', 'RTI', 'SAB', 'SAI', 'SAR', 'SAT', 'SIB', 'SIR', 'SIT', 'SRI', 'TAB', 'TAI', 'TAR', 'TAS', 'TIB', 'TIS', 'TRA', 'TRI', 'TRS', 'TSI', 'ABIR', 'ABIT', 'ABRI', 'AIRS', 'AIRT', 'AITS', 'ARBS', 'ARIS', 'ARTS', 'ATIS', 'BAIT', 'BARI', 'BARS', 'BART', 'BAST', 'BATS', 'BIAS', 'BIRT', 'BIST', 'BITS', 'BRAS', 'BRAT', 'BRIS', 'BRIT', 'ISBA', 'ITAS', 'RABI', 'RAIS', 'RAIT', 'RAST', 'RATS', 'RIAS', 'RIBS', 'RIST', 'RITA', 'RITS', 'SAIR', 'SARI', 'SART', 'SATI', 'SITA', 'STAB', 'STAR', 'STIB', 'STIR', 'STRA', 'TABI', 'TABS', 'TAIS', 'TARI', 'TARS', 'TIAR', 'TSIA', 'ABRIS', 'ABSIT', 'ABSTR', 'AIRTS', 'ARIST', 'ASTIR', 'BAITS', 'BARIS', 'BASTI', 'BATIS', 'BRAST', 'BRATS', 'BRIST', 'BRITS', 'RABIS', 'RAITS', 'RIBAT', 'SABIR', 'SITAR', 'STAIR', 'STRIA', 'TABIS', 'TARSI', 'TIARS', 'TISAR', 'TRIAS']},
{letters: 'NELGAL', words: ['AGE', 'ALE', 'ALL', 'ALN', 'ANE', 'EAN', 'ELA', 'ELL', 'GAE', 'GAL', 'GAN', 'GEL', 'LAG', 'LAN', 'LEA', 'LEG', 'NAE', 'NAG', 'NEA', 'AGEN', 'ALEN', 'EGAL', 'ENGL', 'GAEL', 'GAEN', 'GALE', 'GALL', 'GANE', 'GEAL', 'GEAN', 'GELL', 'GENA', 'GLEN', 'LAEN', 'LANE', 'LEAL', 'LEAN', 'LENA', 'LENG', 'NAEL', 'NALE', 'NEAL', 'AGNEL', 'ALLEN', 'ANGEL', 'ANGLE', 'EGALL', 'ELLAN', 'GALEN', 'GENAL', 'GLEAN', 'LAGEN', 'LEGAL', 'NAGEL', 'LANGEL', 'LANGLE', 'LEGLAN']},
{letters: 'ZPYELA', words: ['ALE', 'ALP', 'ALY', 'APE', 'APL', 'AYE', 'ELA', 'EPA', 'EYL', 'LAP', 'LAY', 'LEA', 'LEP', 'LEY', 'LEZ', 'LYE', 'PAL', 'PAY', 'PEA', 'PEL', 'PLY', 'PYA', 'PYE', 'YAP', 'YEA', 'YEP', 'ZAP', 'ZEL', 'ZEP', 'ALEP', 'LAZE', 'LAZY', 'LEAP', 'LEPA', 'PALE', 'PALY', 'PAYE', 'PEAL', 'PELA', 'PLAY', 'PLEA', 'PYAL', 'PYLA', 'YALE', 'YELP', 'ZEAL', 'AYELP']},
{letters: 'BPATET', words: ['ABT', 'APE', 'APT', 'ATE', 'ATP', 'BAE', 'BAP', 'BAT', 'BET', 'EAT', 'EPA', 'ETA', 'PAT', 'PEA', 'PET', 'PTE', 'PTT', 'TAB', 'TAE', 'TAP', 'TAT', 'TEA', 'TET', 'ABET', 'ATTE', 'BATE', 'BATT', 'BEAT', 'BETA', 'PATE', 'PATT', 'PEAT', 'PEBA', 'PETA', 'TAPE', 'TATE', 'TEAP', 'TEAT', 'TEPA', 'BEPAT', 'BETTA', 'TABET', 'TAPET']},
{letters: 'OGTTOL', words: ['GOL', 'GOO', 'GOT', 'GTT', 'LOG', 'LOO', 'LOT', 'OOT', 'OTO', 'TGT', 'TLO', 'TOG', 'TOL', 'TOO', 'TOT', 'GOOL', 'GOTO', 'LOGO', 'LOOT', 'LOTO', 'OTTO', 'TOGO', 'TOGT', 'TOLT', 'TOOL', 'TOOT', 'TOTO', 'LOTTO']},
{letters: 'DPVITN', words: ['DIN', 'DIP', 'DIT', 'IDP', 'ITD', 'NID', 'NIP', 'NIT', 'PDN', 'PID', 'PIN', 'PIT', 'TID', 'TIN', 'TIP', 'TPD', 'TPI', 'VID', 'VIN', 'VIP', 'DINT', 'DIPT', 'PIND', 'PINT', 'TIND', 'VINT']},
{letters: 'BNAUIP', words: ['ABN', 'ABU', 'AIN', 'ANU', 'BAI', 'BAN', 'BAP', 'BIN', 'BUN', 'IBA', 'NAB', 'NAP', 'NIB', 'NIP', 'NUB', 'PAN', 'PAU', 'PIA', 'PIN', 'PUA', 'PUB', 'PUN', 'UBI', 'UNA', 'UNI', 'UNP', 'AINU', 'BAIN', 'BANI', 'BAPU', 'BAUN', 'BUNA', 'NABU', 'NAIB', 'NAPU', 'NIPA', 'PAIN', 'PIAN', 'PIUA', 'PUAN', 'PUNA', 'UNAI', 'AUBIN', 'BUNIA', 'NUBIA', 'PUBIAN']},
{letters: 'SEREEN', words: ['EEN', 'EER', 'ENE', 'ENS', 'ERE', 'ERS', 'ESE', 'ESR', 'REE', 'REN', 'SEE', 'ENES', 'ENSE', 'ERES', 'ERNE', 'ERSE', 'ESNE', 'NERE', 'NESE', 'REEN', 'REES', 'RENS', 'SEEN', 'SEER', 'SENE', 'SERE', 'SNEE', 'ESERE', 'NEESE', 'REENS', 'REESE', 'RENES', 'RESEE', 'SNEER', 'RESEEN', 'RESENE', 'SERENE']},
{letters: 'GENNOT', words: ['EGO', 'EON', 'GEO', 'GET', 'GOE', 'GON', 'GOT', 'GTE', 'NEO', 'NET', 'NNE', 'NOG', 'NON', 'NOT', 'ONE', 'ONT', 'TEG', 'TEN', 'TGN', 'TOE', 'TOG', 'TON', 'ENTO', 'ETON', 'GENT', 'GOEN', 'GONE', 'GOTE', 'NEON', 'NONE', 'NONG', 'NOTE', 'TENG', 'TOGE', 'TONE', 'TONG', 'TONN', 'GONNE', 'NONET', 'TENNO', 'TENON', 'TONNE']},
{letters: 'LTOOSF', words: ['FLO', 'FOO', 'FOT', 'LOF', 'LOO', 'LOS', 'LOT', 'LST', 'OFO', 'OFT', 'OOF', 'OOS', 'OOT', 'OTO', 'SLT', 'SOL', 'SOT', 'TLO', 'TOL', 'TOO', 'TOS', 'FLOT', 'FOOL', 'FOOS', 'FOOT', 'FOTS', 'LOFT', 'LOOF', 'LOOS', 'LOOT', 'LOST', 'LOTO', 'LOTS', 'OOFS', 'OOTS', 'OSLO', 'SLOO', 'SLOT', 'SOFT', 'SOLO', 'SOOL', 'SOOT', 'STOF', 'TOOL', 'FLOTS', 'FOOLS', 'FOOTS', 'LOFTS', 'LOOFS', 'LOOTS', 'LOTOS', 'SFOOT', 'SLOOT', 'SOTOL', 'STOOF', 'STOOL', 'TOOLS']},
];

console.log("games loaded");